swagger: "2.0"
info:
  description: Produktanbieter-Darlehensdaten API
  title: PADD API
  version: 0.0.1
schemes:
- http
produces:
- application/json
consumes:
- application/json

# Pfade und Ressourcen
paths:
  /darlehensdaten:
    post:
      summary: Anfrage von Darlehensdaten
      description: TBD
      operationId: postDarlehensdatenAnfrage
      parameters:
        - name: anfrage
          in: body
          required: true
          schema:
            $ref: '#/definitions/DarlehensdatenAnfrage'

      responses:
        200:
          description: Erfolgreiche Antwort
          schema:
            $ref: '#/definitions/DarlehensdatenAntwort'
        default:
          description: unspezifizierter Fehler

# Objektdefinitionen
definitions:
  DarlehensId:
    type: string
    description: |
      Eindeutige ID des Darlehens beim Produktanbieter, z.B. Darlehensnummer, Kontonummer oder IBAN.

  PartnerId:
    type: string
    description: |
      Die ID eines Partners im Europace2 System

  Partner:
    type: object
    properties:
      partnerId:
        $ref: '#/definitions/PartnerId'

  Antragsteller:
    description: Daten eines Antragsteller
    type: object
    properties:
      id:
        description: Eindeutiger Identifier des Antragstellers im Europace 2 Systems
        type: string
      vorname:
        type: string
      nachname:
        type: string
      geburtsdatum:
        description: Geburtsdatum nach RFC3339 1973-03-29
        type: date

  Immobilie:
    description: Daten zur bestehenden Immobilie
    properties:
      plz:
        type: string
      ort:
        type: string
      strasse:
        type: string

  DarlehensdatenAnfrage:
    type: object
    properties:
      darlehensId:
        $ref: '#/definitions/DarlehensId'
      kundenBetreuer:
        $ref: '#/definitions/Partner'
      bearbeiter:
        $ref: '#/definitions/Partner'
      antragsteller:
        type: array
        items:
          $ref: '#/definitions/Antragsteller'

  DarlehensdatenAntwort:
    type: object
    properties:
      darlehensId:
        $ref: '#/definitions/DarlehensId'


